### ISSUE TITLE
Persistent dismissal duration

### ISSUE THREAD

**Issue by benignant** [YahnisElsts/admin-notices#2]
What do you think about adding an optional dismissal duration parameter to `persistentlyDismissible()`? After the length of time indicated, the notice would no longer be considered dismissed. I believe this can be done in a backwards compatible way. Would you accept a pull request for such a feature? I wouldn't be able to provide tests however.

**Comment by YahnisElsts** [comment]
That seems like a reasonable addition. Yes, I would probably accept a pull request.
