### ISSUE TITLE
Admin notices and WP Background Processing

### ISSUE THREAD

**Issue by manguoes** [YahnisElsts/admin-notices#5]
Hi.

I'm trying to use this library in my plugin together with the [WP Background Processing](https://github.com/deliciousbrains/wp-background-processing) library, but i simply can't get it to work.

My code looks something like this:
```
class My_Process extends WP_Background_Process{
        protected $action = 'my_process';

	protected function task($item){
             // Doing the process...
             return false;
	}

	protected function complete(){
             parent::complete();
 
             \YeEasyAdminNotices\V1\AdminNotice::create()
                ->success('Complete!')
                ->dismissible()
                ->showOnNextPage();
	}
}
```

I have tested everything it seems. I have tried to set the `onPage` method together with both the `show` or `showOnNextPage` methods but the notice isn't showing after the background process is complete.

`AdminNotice.php` is being included in the top of my plugin and the `WP_Background_Process` is initiated via the action `plugins_loaded `

I have also verified that the `complete()` function is being called, so that's not the problem. 

Do you have any clue on what could be wrong?

**Comment by YahnisElsts** [comment]
The `showOnNextPage` method saves the notice to be shown in a user meta key. Does `complete` run in the context of the current user? If it doesn't then `showOnNextPage` isn't going to work in this case.

**Comment by manguoes** [comment]
Thank you for your answer.
It turned out that initiating `WP_Background_Process ` on `plugins_loaded` is too early since the context of the current user hasn't been loaded yet at that point, as you hinted. Hooking on to the `init` action instead made everything work.

Thanks for your help!
